services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-management-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge